name: dispatch receiver

on: [repository_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: dispatch trigger
      if: github.event.action == 'making-framework'
      run: |
        sh ./update_version.sh
        sh ./publish_podspec.sh ${{ secrets.ACCESS_TOKEN }}
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
